"""Docx exporter module for PaperMint."""

from __future__ import annotations

import io

import docx
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches

from papermint.config import APP_NAME
from papermint.models import Citation


def export_docx(citations: list[Citation], title: str = "Extracted References") -> io.BytesIO:
    """Export citations as a formatted Word document.

    Args:
        citations: List of Citation objects to export.
        title: Document title.

    Returns:
        A BytesIO object containing the Word document data.
    """
    doc = docx.Document()

    # Title
    heading = doc.add_heading(title, level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    subtitle = doc.add_paragraph(f"Generated by {APP_NAME} - {len(citations)} citations extracted")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.style = "Subtitle"

    doc.add_paragraph()  # Spacer

    for i, citation in enumerate(citations, 1):
        p = doc.add_paragraph()
        p.paragraph_format.left_indent = Inches(0.5)
        p.paragraph_format.first_line_indent = Inches(-0.5)

        # Number
        p.add_run(f"[{i}] ")

        # Authors (Year)
        author_string = ", ".join(author.full_name for author in citation.authors)
        if not author_string:
            author_string = "Unknown Author"

        authors_run = p.add_run(author_string)
        authors_run.bold = True

        year_str = f" ({citation.year}). " if citation.year else ". "
        p.add_run(year_str)

        # Title
        if citation.title:
            p.add_run(f"{citation.title}. ")

        # Journal, Volume(Issue), Pages
        if citation.journal:
            journal_run = p.add_run(f"{citation.journal}")
            journal_run.italic = True
            if citation.volume:
                vol_issue_str = f", {citation.volume}"
                if citation.issue:
                    vol_issue_str += f"({citation.issue})"
                p.add_run(vol_issue_str)

            if citation.pages:
                p.add_run(f", {citation.pages}")

            p.add_run(". ")

        # DOI
        if citation.doi:
            p.add_run(f"DOI: {citation.doi}")

    output = io.BytesIO()
    doc.save(output)
    output.seek(0)

    return output
