"""PDF exporter module for PaperMint."""

from __future__ import annotations

import io

from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate

from papermint.config import APP_NAME
from papermint.models import Citation


def export_pdf(citations: list[Citation], title: str = "Extracted References") -> io.BytesIO:
    """Export citations as a formatted PDF document.

    Args:
        citations: List of Citation objects to export.
        title: Document title.

    Returns:
        A BytesIO object containing the PDF document data.
    """
    output = io.BytesIO()
    doc = SimpleDocTemplate(
        output,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Heading1"], alignment=TA_CENTER, fontSize=18, spaceAfter=12
    )

    subtitle_style = ParagraphStyle(
        "SubtitleStyle",
        parent=styles["Normal"],
        alignment=TA_CENTER,
        fontSize=12,
        textColor="gray",
        spaceAfter=24,
    )

    citation_style = ParagraphStyle(
        "CitationStyle",
        parent=styles["Normal"],
        alignment=TA_LEFT,
        leftIndent=36,
        firstLineIndent=-36,
        spaceAfter=12,
        leading=14,
    )

    story = []

    # Header
    story.append(Paragraph(title, title_style))
    story.append(
        Paragraph(f"Generated by {APP_NAME} - {len(citations)} citations extracted", subtitle_style)
    )

    # Citations
    for i, citation in enumerate(citations, 1):
        # Format text
        author_string = ", ".join(author.full_name for author in citation.authors)
        if not author_string:
            author_string = "Unknown Author"

        text_parts = [f"<b>[{i}] {author_string}</b>"]

        if citation.year:
            text_parts.append(f"({citation.year}).")
        else:
            text_parts.append(".")

        if citation.title:
            text_parts.append(f"{citation.title}.")

        if citation.journal:
            journal_part = f"<i>{citation.journal}</i>"

            vol_issue_pages = []
            if citation.volume:
                v = str(citation.volume)
                if citation.issue:
                    v += f"({citation.issue})"
                vol_issue_pages.append(v)
            if citation.pages:
                vol_issue_pages.append(str(citation.pages))

            if vol_issue_pages:
                journal_part += ", " + ", ".join(vol_issue_pages)

            journal_part += "."
            text_parts.append(journal_part)

        if citation.doi:
            text_parts.append(f"DOI: {citation.doi}")

        citation_text = " ".join(text_parts)
        story.append(Paragraph(citation_text, citation_style))

    doc.build(story)
    output.seek(0)
    return output
